Oop
IvanSukhanov4/common pull request #8
Opened 2019-10-16 20:05 UTC by IvanSukhanov4

2019-10-22 07:21 UTC, ekut2104 requested changes
і рядок 374 Свариться лінтер. варто звернути увагу.
Чи доцільно тут використовувати цілий клас?

2019-10-22 07:21 UTC, ekut2104 commented on oop/homework.py
>          return sum([Wall.wall_square() for Wall in self.__walls])
Свариться лінтер. варто звернути увагу

2019-10-22 07:21 UTC, ekut2104 commented on oop/homework.py
>          return sum([Window.window_square() for Window in self.__windows])
Свариться лінтер. варто звернути увагу

2019-10-22 15:39 UTC, IvanSukhanov4 commented on oop/homework.py
>          return sum([Wall.wall_square() for Wall in self.__walls])
Исправил.Проблема, видимо, из-за большой буквы была.
Но не понял про какую строку идет речь"Чи доцільно тут використовувати цілий клас?". Вроде кажется везде логично)

2019-10-23 06:35 UTC, ekut2104 commented on oop/homework.py
>          return sum([Wall.wall_square() for Wall in self.__walls])
Wall - це клас)
в чому різниця  між Wall.wall_square() та wall.wall_square() ?

2019-10-23 06:37 UTC, ekut2104 commented on oop/homework.py
>          return sum([Wall.wall_square() for Wall in self.__walls])
Wall в тебе називається клас) тому питання чи дозільно тут його використовувати)

2019-10-23 06:38 UTC, ekut2104 approved these changes

2019-10-26 19:26 UTC, merged